### ISSUE TITLE
Links are broken?

### ISSUE THREAD

**Issue by isaacschaal** [joelgrus/shirts#1]
Have you taken this down? I used it for a class and really liked it and am trying to show it to some students, but can't seem to find the blog posts. I get a "Page not Found" error on your website.

**Comment by joelgrus** [comment]
I took down a lot of old blog posts, but I should have left that one up, I like it

it's back up now

https://joelgrus.com/2013/06/19/t-shirts-feminism-parenting-and-data-science-part-1-colors/
https://joelgrus.com/2013/06/24/t-shirts-feminism-parenting-and-data-science-part-2-eigenshirts/

**Comment by isaacschaal** [comment]
I like it to :) Thanks!
